# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LuBqMsnfUOuh_whXjqLy6w2peJk7lV4I
"""

# ==============================
# 1. IMPORT LIBRARIES
# ==============================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import IsolationForest
from sklearn.linear_model import LinearRegression

# ==============================
# 2. RAW DATA (Simulated)
# ==============================
# Simulating structured + unstructured-like dataset
np.random.seed(42)

data = pd.DataFrame({
    "date": pd.date_range(start="2024-01-01", periods=100),
    "sales": np.random.normal(200, 25, 100),
    "region": np.random.choice(["North", "South", "East", "West"], 100)
})

# Inject anomaly
data.loc[95:99, "sales"] = data.loc[95:99, "sales"] * 2

# ==============================
# 3. AI PROCESSING
# ==============================

# --- (A) Pattern Detection / Trend ---
data["time_index"] = np.arange(len(data))
model = LinearRegression()
model.fit(data[["time_index"]], data["sales"])

data["trend"] = model.predict(data[["time_index"]])

# --- (B) Anomaly Detection ---
iso_forest = IsolationForest(contamination=0.05)
data["anomaly"] = iso_forest.fit_predict(data[["sales"]])

# Convert anomaly labels (-1 = anomaly)
data["anomaly_flag"] = data["anomaly"].apply(lambda x: 1 if x == -1 else 0)

# --- (C) Forecasting ---
future_days = 10
future_index = np.arange(len(data), len(data) + future_days).reshape(-1, 1)
forecast = model.predict(future_index)

# ==============================
# 4. SMART VISUALIZATION
# ==============================

plt.figure(figsize=(12, 6))

# Actual sales
plt.plot(data["date"], data["sales"], label="Actual Sales")

# Trend line
plt.plot(data["date"], data["trend"], linestyle="dashed", label="Trend")

# Highlight anomalies
anomalies = data[data["anomaly_flag"] == 1]
plt.scatter(anomalies["date"], anomalies["sales"], label="Anomalies")

# Forecast plot
future_dates = pd.date_range(start=data["date"].iloc[-1], periods=future_days+1)[1:]
plt.plot(future_dates, forecast, linestyle="dotted", label="Forecast")

plt.title("AI-Powered Data Visualization Pipeline")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.legend()
plt.grid()

plt.show()

# ==============================
# 5. ACTIONABLE INSIGHTS
# ==============================

print("\n--- ACTIONABLE INSIGHTS ---")

# Trend insight
if model.coef_[0] > 0:
    print("📈 Sales are trending upward.")
else:
    print("📉 Sales are trending downward.")

# Anomaly insight
num_anomalies = data["anomaly_flag"].sum()
print(f"⚠️ Detected {num_anomalies} anomalies in sales data.")

# Forecast insight
print(f"🔮 Next {future_days} days forecast (avg): {forecast.mean():.2f}")

# Business recommendation
if forecast.mean() > data["sales"].mean():
    print("✅ Recommendation: Increase inventory/marketing.")
else:
    print("⚠️ Recommendation: Optimize costs and investigate demand drop.")