import json
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime
from plotly.subplots import make_subplots

# =====================================================================
# 1. INGESTION LAYER (Simulating AI Agent Canvas Log Stream)
# =====================================================================
def fetch_ai_dashboard_configs():
    """
    Simulates ingesting raw JSON metadata emitted by an autonomous AI 
    Insights Agent whenever it generates a dynamic visual dashboard for a user.
    """
    print("[Ingestion] Fetching unstructured layout payloads from AI Agent registry...")
    
    # Raw log telemetry containing the AI's structural design and execution stats
    raw_canvas_logs = [
        {
            "dashboard_id": "DB-901",
            "timestamp": "2026-05-20T11:14:02",
            "user_intent": "Show me Q1 paid media performance and CPA trends",
            "generated_layout": '{"theme": "dark", "grid_type": "fluid", "widgets": [{"type": "bar", "metric": "CPA"}, {"type": "line", "metric": "spend"}, {"type": "kpi", "metric": "total_conversions"}]}',
            "ai_generated_sql": "SELECT date, cpa, spend, conversions FROM analytics.fct_marketing WHERE date >= '2026-01-01'",
            "query_execution_ms": 1420,
            "user_rating_score": 5
        },
        {
            "dashboard_id": "DB-902",
            "timestamp": "2026-05-20T11:30:15",
            "user_intent": "Predictive churn risk overview for enterprise accounts",
            "generated_layout": '{"theme": "dark", "grid_type": "fixed", "widgets": [{"type": "scatter", "metric": "pCLV_vs_churn"}, {"type": "table", "metric": "risk_accounts"}]}',
            "ai_generated_sql": "SELECT customer_id, churn_probability, predicted_clv FROM analytics.fct_predictions WHERE segments = 'Enterprise'",
            "query_execution_ms": 2890,
            "user_rating_score": 4
        },
        {
            "dashboard_id": "DB-903",
            "timestamp": "2026-05-20T12:01:44",
            "user_intent": "Where are our website drop-offs happening this week?",
            "generated_layout": '{"theme": "light", "grid_type": "fluid", "widgets": [{"type": "funnel", "metric": "conversion_funnel"}, {"type": "bar", "metric": "bounce_by_page"}, {"type": "pie", "metric": "device_mix"}, {"type": "kpi", "metric": "avg_session_duration"}]}',
            "ai_generated_sql": "SELECT step, count FROM analytics.web_traffic WHERE timestamp >= '2026-05-13' GROUP BY 1",
            "query_execution_ms": 940,
            "user_rating_score": 2
        },
        {
            "dashboard_id": "DB-904",
            "timestamp": "2026-05-20T13:45:10",
            "user_intent": "Executive revenue summary wrap-up",
            "generated_layout": '{"theme": "dark", "grid_type": "fluid", "widgets": [{"type": "kpi", "metric": "mrr"}, {"type": "kpi", "metric": "arr"}]}',
            "ai_generated_sql": "SELECT SUM(mrr), SUM(arr) FROM analytics.fct_finance",
            "query_execution_ms": 410,
            "user_rating_score": 5
        }
    ]
    
    return pd.DataFrame(raw_canvas_logs)

# =====================================================================
# 2. TRANSFORMATION LAYER (Meta-Schema Parsing & Feature Extraction)
# =====================================================================
def transform_dashboard_telemetry(df):
    """
    Parses nested JSON layout payloads generated by the AI model.
    Extracts structural design telemetry to evaluate generation quality.
    """
    print("[Transformation] Flattening dynamic JSON schemas and calculating layout complexity...")
    
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    
    # Lists to capture dynamically extracted configurations
    widget_counts = []
    ui_themes = []
    layout_types = []
    
    # Iterate through row records and extract properties safely from the AI's design schema
    for _, row in df.iterrows():
        try:
            layout_meta = json.loads(row['generated_layout'])
            widget_counts.append(len(layout_meta.get('widgets', [])))
            ui_themes.append(layout_meta.get('theme', 'unknown'))
            layout_types.append(layout_meta.get('grid_type', 'fluid'))
        except (json.JSONDecodeError, TypeError):
            widget_counts.append(0)
            ui_themes.append('malformed')
            layout_types.append('unknown')
            
    # Assign newly structured metrics back to core DataFrame
    df['total_widgets_rendered'] = widget_counts
    df['ui_theme_selected'] = ui_themes
    df['layout_grid_type'] = layout_types
    
    # Derive an abstract generation efficiency index: query time cost per layout widget
    df['latency_per_widget_ms'] = df['query_execution_ms'] / df['total_widgets_rendered']
    
    return df

# =====================================================================
# 3. MODERN META-ANALYTICS VISUALIZATION
# =====================================================================
def render_meta_analytics_dashboard(df):
    """
    Renders an executive operational dashboard visualizing the health, 
    complexity, and user acceptance of AI-generated user interfaces.
    """
    print("[Visualization] Instantiating AI-Generated Dashboard Performance Cockpit...")
    
    # Create subplots matrix
    fig = make_subplots(
        rows=2, cols=2,
        subplot_titles=(
            'Dashboard Generation Latency vs. Layout Complexity',
            'User Satisfaction (CSAT) by Interface Theme',
            'Distribution of Automated Grid Layout Frameworks',
            'AI Ingestion Health Matrix'
        ),
        specs=[[{"type": "xy"}, {"type": "xy"}],
               [{"type": "bar"}, {"type": "domain"}]]
    )

    # Plot 1: Latency vs Complexity (Top Left)
    fig.add_trace(
        go.Scatter(
            x=df['total_widgets_rendered'],
            y=df['query_execution_ms'],
            mode='markers+text',
            text=df['dashboard_id'],
            textposition="top left",
            marker=dict(size=15, color='#00CC96', line=dict(width=1.5, color='white')),
            name="Dashboards"
        ),
        row=1, col=1
    )
    fig.update_xaxes(title_text="Number of Rendered Widgets", row=1, col=1)
    fig.update_yaxes(title_text="Warehouse Query Latency (ms)", row=1, col=1)

    # Plot 2: CSAT by UI Theme (Top Right)
    theme_perf = df.groupby('ui_theme_selected')['user_rating_score'].mean().reset_index()
    fig.add_trace(
        go.Bar(
            x=theme_perf['ui_theme_selected'],
            y=theme_perf['user_rating_score'],
            marker_color=['#AB63FA', '#636EFA'],
            name="Avg Score"
        ),
        row=1, col=2
    )
    fig.update_yaxes(title_text="Average Score (1-5)", row=1, col=2)

    # Plot 3: Grid System Selection Mix (Bottom Left)
    grid_counts = df['layout_grid_type'].value_counts().reset_index()
    fig.add_trace(
        go.Bar(
            x=grid_counts['layout_grid_type'],
            y=grid_counts['count'],
            marker_color='#19D3BF',
            name="Layout Count"
        ),
        row=2, col=1
    )
    fig.update_yaxes(title_text="Generation Volume", row=2, col=1)

    # Plot 4: Operational Metrics Card (Bottom Right)
    avg_render_latency = df['query_execution_ms'].mean()
    fig.add_trace(
        go.Indicator(
            mode="number",
            value=avg_render_latency,
            number={'suffix': " ms", 'valueformat': ".0f"},
            title={"text": "Average AI SQL Execution Overhead"}
        ),
        row=2, col=2
    )

    # Unified Layout Stylings
    fig.update_layout(
        title_text="Autonomous UI Factory: Dynamic Dashboard Telemetry Analytics",
        template="plotly_dark",
        showlegend=False,
        height=850,
        width=1200
    )
    
    fig.show()

# =====================================================================
# PIPELINE RUNNER ENGINE
# =====================================================================
if __name__ == "__main__":
    print("--- Commencing AI Dashboard Ingestion Telemetry Pipeline ---")
    
    # 1. Ingest unstructured metadata schemas from AI Canvas Logs
    raw_canvas_data = fetch_ai_dashboard_configs()
    
    # 2. Flatten dynamic configurations & extract analytics-on-analytics KPIs
    enriched_telemetry = transform_dashboard_telemetry(raw_canvas_data)
    
    # Print out a clear representation of parsed meta-analytics fields
    print("\n--- Parsed AI Dashboard Telemetry Matrix ---")
    print(enriched_telemetry[['dashboard_id', 'total_widgets_rendered', 'ui_theme_selected', 'query_execution_ms', 'user_rating_score']])
    print("---------------------------------------------\n")
    
    # 3. Render the interactive meta-dashboard application
    render_meta_analytics_dashboard(enriched_telemetry)
    
    print("--- Telemetry Pipeline Successfully Executed ---")