# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PtrEwYluFhjgoFh3J0_7sNrbcQo6ED7n
"""

import pandas as pd
import numpy as np
import plotly.express as px
from textblob import TextBlob

# ==========================================
# MODULE 1: RFM ANALYSIS
# ==========================================
def perform_rfm_analysis(df):
    df['OrderDate'] = pd.to_datetime(df['OrderDate'])
    snapshot_date = df['OrderDate'].max() + pd.Timedelta(days=1)

    rfm = df.groupby('CustomerID').agg({
        'OrderDate': lambda x: (snapshot_date - x.max()).days,
        'CustomerID': 'count',
        'TransactionAmount': 'sum'
    }).rename(columns={'OrderDate': 'Recency', 'CustomerID': 'Frequency', 'TransactionAmount': 'Monetary'})

    # Handle small datasets: rank method ensures we can cut even with few rows
    rfm['R_Score'] = pd.qcut(rfm['Recency'].rank(method='first'), 5, labels=[5, 4, 3, 2, 1])
    rfm['F_Score'] = pd.qcut(rfm['Frequency'].rank(method='first'), 5, labels=[1, 2, 3, 4, 5])
    rfm['M_Score'] = pd.qcut(rfm['Monetary'].rank(method='first'), 5, labels=[1, 2, 3, 4, 5])

    def segment_users(row):
        score = int(row['R_Score']) + int(row['F_Score']) + int(row['M_Score'])
        if score >= 12: return 'Champions'
        if score <= 6: return 'At Risk'
        return 'Loyal'

    rfm['Segment'] = rfm.apply(segment_users, axis=1)
    return rfm

# ==========================================
# MODULE 2: SENTIMENT ANALYSIS
# ==========================================
def analyze_sentiment(text_list):
    results = []
    for text in text_list:
        score = TextBlob(text).sentiment.polarity
        sentiment = 'Positive' if score > 0.1 else ('Negative' if score < -0.1 else 'Neutral')
        results.append({'text': text, 'score': score, 'sentiment': sentiment})
    return pd.DataFrame(results)

# ==========================================
# MODULE 3: MARKETING ROI
# ==========================================
def calculate_marketing_metrics(spend, revenue, customers_acquired, churn_rate):
    roi = ((revenue - spend) / spend) * 100
    cpa = spend / customers_acquired
    clv = (revenue / customers_acquired) / churn_rate

    return pd.DataFrame({
        'Metric': ['ROI (%)', 'CPA ($)', 'CLV ($)'],
        'Value': [round(roi, 2), round(cpa, 2), round(clv, 2)]
    })

# ==========================================
# SYSTEM EXECUTION (MAIN)
# ==========================================
def main():
    # 1. RFM Implementation
    raw_data = {
        'CustomerID': [101, 102, 103, 104, 105],
        'OrderDate': ['2026-04-01', '2026-01-15', '2026-04-28', '2025-12-01', '2026-04-20'],
        'TransactionAmount': [500, 150, 600, 50, 300]
    }
    df_rfm = pd.DataFrame(raw_data)
    rfm_results = perform_rfm_analysis(df_rfm)

    # 2. Sentiment Implementation
    social_posts = ["Love the product!", "Worst experience ever.", "It's fine."]
    sentiment_df = analyze_sentiment(social_posts)

    # 3. Marketing ROI Implementation
    mkt_metrics = calculate_marketing_metrics(5000, 15000, 200, 0.1)

    # OUTPUTS
    print("--- CUSTOMER SEGMENTS ---")
    print(rfm_results[['Segment', 'Monetary']])
    print("\n--- SENTIMENT SCORES ---")
    print(sentiment_df)

    # Visuals
    fig1 = px.pie(rfm_results, names='Segment', title="Customer Segmentation Distribution")
    fig2 = px.bar(mkt_metrics, x='Metric', y='Value', color='Metric', title="Campaign ROI Dashboard")

    fig1.show()
    fig2.show()

if __name__ == "__main__":
    main()